# Generated by Django 3.2.5 on 2021-12-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserM',
        ),
    ]
